"use client";
import "./globals.css";
import { roboto } from "./font";

import styles from "./styles.module.scss";
import classnames from "classnames";

import { CartIcon } from "../component/Icon/Cart";
import Link from "next/link";
import { useSelector } from "react-redux";
import { StoreProvider } from "@/business/StoreProvider";
import { selectAllTicket } from "@/business/feature/cart/selector";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = () => {
  const ticketAmount = useSelector(selectAllTicket);

  return (
    <header className={classnames(styles.header)}>
      <div className={classnames(styles.nav__wrapper)}>
        <div>
          <Link href="/">Билетопоиск</Link>
        </div>
        <div className={classnames(styles.counter__wrapper)}>
          <div className={classnames(styles.counter)}>{ticketAmount}</div>
          <Link href="/cart">
            <CartIcon color="#FFFFFF" />
          </Link>
        </div>
      </div>
    </header>
  );
};

const Footer = () => {
  return (
    <footer className={classnames(styles.footer)}>
      <div className={classnames(styles.nav__wrapper)}>
        <div>
          <Link href="/faq">Вопросы-ответы</Link>
        </div>
        <Link href="/about">О нас</Link>
      </div>
    </footer>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <div
          className={classnames(styles.container, styles.container__main_page)}
        >
          <StoreProvider>
            <Header />
            <div className={classnames(styles.main)}>{children}</div>
            <Footer />
          </StoreProvider>
        </div>
      </body>
    </html>
  );
}
