import "./globals.css";
import { roboto } from "./font";

import styles from "./styles.module.scss";
import classnames from "classnames";

import { CartIcon } from "../component/icon/Cart";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//TODO:next link for ,ain and carrt
const Header = () => {
  return (
    <header className={classnames(styles.header)}>
      <div className={classnames(styles.nav__wrapper)}>
        <div> Билетопоиск</div>
        <div>
          <CartIcon color="#FFFFFF" />
        </div>
      </div>
    </header>
  );
};

const Footer = () => {
  return (
    <footer className={classnames(styles.footer)}>
      <div className={classnames(styles.nav__wrapper)}>
        <div> Вопросы-ответы</div>
        <div>О нас</div>
      </div>
    </footer>
  );
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <div className={classnames(styles.container)}>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
